Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using TarasDzivikPetProject.Domain;

namespace TarasDzivikPetProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            // Для прикладу виведемо на сторінку адмінки список всіх послуг які в нас є на сайті
            return View(dataManager.VehicleItems.GetVehicleItem());
        }
    }
}

Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using TarasDzivikPetProject.Domain;
using TarasDzivikPetProject.Domain.Entities;
using TarasDzivikPetProject.Service;

namespace TarasDzivikPetProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        // Тут ми передаємо наше кодове слово, шукаємо його в БД і передаємо його у View
        public IActionResult Edit(string codeword)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeword);
            return View(entity);
        }

        [Area("Admin")]
        [HttpPost] // Тут нам приходить "TextField model"
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid) // Далі ми провіряємо її валідність
            {
                dataManager.TextFields.SaveTextField(model); /* зберігаємо в БД нашу "model" і перенеправляємо
                                                              * користувача в Areas\Admin\Controllers\HomeController*/
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Areas/Admin/Controllers/VehicleItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using TarasDzivikPetProject.Domain;
using TarasDzivikPetProject.Domain.Entities;
using TarasDzivikPetProject.Service;
using System.IO;

namespace TarasDzivikPetProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VehicleItemController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostEnvironment; // хостинг для зберігання титульних картинок
        public VehicleItemController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
        {
            this.dataManager = dataManager;
            this.hostEnvironment = hostEnvironment;
        }

        public IActionResult Edit(int id) // По ідентифікатору ми шукаємо послугу в БД. Якщо не знайдена то ми створюємо нову.
        {
            var entity = id == default ? new VehicleItem() : dataManager.VehicleItems.GetVehicleItemById(id);
            return View(entity);
        }

        [Area("Admin")]
        [HttpPost]
        public IActionResult Edit(VehicleItem model, IFormFile titleImageFile) // вхідний файл не провіряється (не сек'юрно)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path
                        .Combine(hostEnvironment.WebRootPath, "images/VehicleImages/", titleImageFile.FileName),
                            FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.VehicleItems.SaveVehicleItem(model);
                return RedirectToAction(nameof(HomeController.Index),
                    nameof(HomeController).CutController());
            }
            return View(model);
        }
        [Area("Admin")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            dataManager.VehicleItems.DeleteVehicleItem(id);
            return RedirectToAction(nameof(HomeController.Index),
                nameof(HomeController).CutController());
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using TarasDzivikPetProject.Domain;

namespace TarasDzivikPetProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult BuyVehicle()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("BuyVehicle"));
        }

        public IActionResult RentVehicle()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("RentVehicle"));
        }
        public IActionResult LoanCalculator()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("LoanCalculator"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("Contacts"));
        }
    }
}

Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using TarasDzivikPetProject.Domain;

namespace TarasDzivikPetProject.Controllers
{
    public class VehicleController : Controller
    {
        private readonly DataManager dataManager;
        public VehicleController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        /* нижче логіка так, що ми очікуємо на вході параметр типу ІД.
         якщо ми не хочему якусь конкретну послугу, а усі, то дефолтне значення у нас пусте
        і відповідно пропускаємо ІФ провірку, через ВьюБеґ записуємо туди модель "PageVehicle"
        і в якості самої моделі для представлення в нас буде список всіх послуг (GetVehicleItems)
        
        Мабуть правельніше було зробити список всіх послуг через вью/модел, но поки що залишу так*/

        public IActionResult Index(int id)
        {
            if (id != default)
            {
                return View("Show", dataManager.VehicleItems.GetVehicleItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageVehicle");
            return View(dataManager.VehicleItems.GetVehicleItem());
        }
    }
}

Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<VehicleItem>
@{ 
    string strTitle = "Панель адміністратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Весь транспорт</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="VehicleItem" asp-action="Edit" asp-route-id="">Добавити транспорт</a>
        </div>
        <div>
            @if (Model.Any())
            {
                <div>
                    @foreach (VehicleItem entity in Model)
                    {
                        <div>
                            <a asp-area="Admin" asp-controller="VehicleItem" asp-action="Edit" asp-route-id="@entity.VehicleId">Редагувати</a>
                            |
                            <form style="display: inline-block" id="from-@entity.VehicleId" asp-area="Admin" asp-controller="VehicleItem" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@entity.VehicleId"/>
                                <a href="#" onclick="document.getElementById('from-@entity.VehicleId').submit()">Видалити</a>
                            </form>
                            |
                            <a asp-area="" asp-controller="Vehicle" asp-action="Index" asp-route-id="@entity.VehicleId">
                                @($"{entity.Title}")
                            </a>
                        </div>
                    }
                </div>
            }
        </div>
        <div class="div-box">
            <h3>Редагувати сторінку сайту</h3>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeword="PageIndex">Головна</a>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeword="PageVehicle">Транспорт</a>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeword="PageContacts">Контакти</a>
        </div>
        <div class="div-box">
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                <input type="submit" value="Вийти"/>
            </form>
        </div>
    </div>
</div>